import os
import json
import logging
from typing import Tuple, Dict, Any, List
import pandas as pd
import numpy as np

logger = logging.getLogger("DataCleaner")

class DataCleaner:
    """
    Purpose:
        Validate, clean, and analyze datasets generated by DatasetBuilder.
        Generates comprehensive dataset quality reports.
    """
    def __init__(self):
        pass

    def clean(self, df: pd.DataFrame, label_col: str = "label") -> pd.DataFrame:
        """
        Clean the input DataFrame by removing NaNs, removing duplicated rows,
        validating labels, detecting impossible values, and returning a cleaned copy.
        """
        if df.empty:
            logger.warning("Empty DataFrame passed to clean.")
            return df

        initial_len = len(df)
        df_clean = df.copy()

        # 1. Remove duplicated rows (excluding timestamp if possible, but standard drop duplicates is fine)
        df_clean = df_clean.drop_duplicates()
        dup_removed = initial_len - len(df_clean)
        if dup_removed > 0:
            logger.info(f"Removed {dup_removed} duplicate rows.")

        # 2. Detect impossible values and replace/drop
        # e.g., Spread < 0, ATR < 0, or infinite values
        if "spread" in df_clean.columns:
            invalid_spread = (df_clean["spread"] < 0).sum()
            if invalid_spread > 0:
                logger.warning(f"Detected {invalid_spread} rows with negative spread. Fixing to 0.")
                df_clean.loc[df_clean["spread"] < 0, "spread"] = 0.0

        if "atr" in df_clean.columns:
            invalid_atr = (df_clean["atr"] < 0).sum()
            if invalid_atr > 0:
                logger.warning(f"Detected {invalid_atr} rows with negative ATR. Dropping those rows.")
                df_clean = df_clean[df_clean["atr"] >= 0]

        # Replace infinities with NaNs so we can drop/fill them
        df_clean = df_clean.replace([np.inf, -np.inf], np.nan)

        # 3. Handle NaNs
        # Drop rows where the label or target is NaN
        if label_col in df_clean.columns:
            df_clean = df_clean.dropna(subset=[label_col])

        # Fill other NaNs with 0.0 or forward fill
        nan_cols = df_clean.columns[df_clean.isnull().any()].tolist()
        if nan_cols:
            logger.info(f"Features with NaNs detected: {nan_cols}. Filling with 0.0.")
            df_clean = df_clean.fillna(0.0)

        # 4. Normalize categoricals (e.g. label column)
        if label_col in df_clean.columns:
            if df_clean[label_col].dtype == object or isinstance(df_clean[label_col].dtype, pd.CategoricalDtype):
                df_clean[label_col] = df_clean[label_col].astype(str).str.upper().str.strip()

        cleaned_len = len(df_clean)
        logger.info(f"Dataset cleaning completed. Rows: {initial_len} -> {cleaned_len}")
        return df_clean

    def generate_report(
        self,
        df_train: pd.DataFrame,
        df_test: pd.DataFrame,
        label_col: str = "label",
        filepath: str = "reports/dataset_report.html"
    ) -> None:
        """
        Generate reports/dataset_report.html containing feature distributions,
        missing values, class balance, correlation heatmap, and split summaries.
        """
        os.makedirs(os.path.dirname(os.path.abspath(filepath)), exist_ok=True)

        # Calculate class balances
        train_classes = df_train[label_col].value_counts().to_dict() if label_col in df_train.columns else {}
        test_classes = df_test[label_col].value_counts().to_dict() if label_col in df_test.columns else {}

        # Extract numeric columns for correlation matrix
        numeric_cols = df_train.select_dtypes(include=[np.number]).columns.tolist()
        # Exclude constant/degenerate columns
        valid_cols = [c for c in numeric_cols if df_train[c].std() > 1e-6 and c not in [label_col, "target"]]

        # Top 15 correlated features with label/target
        correlations = {}
        if valid_cols and label_col in df_train.columns and df_train[label_col].dtype in [int, float, np.int64, np.float64]:
            corr_series = df_train[valid_cols].corrwith(df_train[label_col])
            correlations = corr_series.dropna().abs().sort_values(ascending=False).head(15).to_dict()
        elif valid_cols and "target" in df_train.columns:
            corr_series = df_train[valid_cols].corrwith(df_train["target"])
            correlations = corr_series.dropna().abs().sort_values(ascending=False).head(15).to_dict()

        # Missing values summary
        missing_summary = df_train.isnull().sum().to_dict()

        # Feature distributions stats
        dist_stats = []
        for col in valid_cols[:20]:  # Limit to top 20 for report simplicity
            dist_stats.append({
                "feature": col,
                "mean": float(df_train[col].mean()),
                "std": float(df_train[col].std()),
                "min": float(df_train[col].min()),
                "max": float(df_train[col].max())
            })

        html_content = f"""<!DOCTYPE html>
<html>
<head>
    <title>Dataset Quality Report</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-50 font-sans p-8">
    <div class="max-w-7xl mx-auto">
        <header class="mb-8 border-b pb-4">
            <h1 class="text-4xl font-bold text-gray-800">Dataset Validation & Quality Report</h1>
            <p class="text-gray-600 mt-2">Comprehensive data validation, split analysis, and feature dependencies</p>
        </header>

        <div class="grid grid-cols-1 md:grid-cols-4 gap-6 mb-8">
            <div class="bg-white p-6 rounded-lg shadow-sm border border-gray-100">
                <h3 class="text-gray-500 text-sm font-semibold">Train Samples</h3>
                <p class="text-3xl font-bold mt-2 text-indigo-600">{len(df_train)}</p>
            </div>
            <div class="bg-white p-6 rounded-lg shadow-sm border border-gray-100">
                <h3 class="text-gray-500 text-sm font-semibold">Test Samples</h3>
                <p class="text-3xl font-bold mt-2 text-green-600">{len(df_test)}</p>
            </div>
            <div class="bg-white p-6 rounded-lg shadow-sm border border-gray-100">
                <h3 class="text-gray-500 text-sm font-semibold">Total Features</h3>
                <p class="text-3xl font-bold mt-2 text-gray-800">{len(valid_cols)}</p>
            </div>
            <div class="bg-white p-6 rounded-lg shadow-sm border border-gray-100">
                <h3 class="text-gray-500 text-sm font-semibold">Missing Values</h3>
                <p class="text-3xl font-bold mt-2 text-red-600">{sum(missing_summary.values())}</p>
            </div>
        </div>

        <div class="grid grid-cols-1 md:grid-cols-2 gap-8 mb-8">
            <div class="bg-white p-6 rounded-lg shadow-sm border border-gray-100">
                <h2 class="text-xl font-bold text-gray-700 mb-4">Class Balance (Train Set)</h2>
                <div class="w-full h-64 flex justify-center">
                    <canvas id="trainClassChart"></canvas>
                </div>
            </div>

            <div class="bg-white p-6 rounded-lg shadow-sm border border-gray-100">
                <h2 class="text-xl font-bold text-gray-700 mb-4">Top Feature Correlations</h2>
                <div class="overflow-x-auto">
                    <table class="min-w-full bg-white text-left text-sm">
                        <thead>
                            <tr class="bg-gray-100">
                                <th class="p-3">Feature</th>
                                <th class="p-3">Abs Correlation Coefficient</th>
                            </tr>
                        </thead>
                        <tbody>
                            {"".join([f'<tr class="border-b"><td class="p-3 font-mono">{k}</td><td class="p-3 text-indigo-600 font-semibold">{v:.4f}</td></tr>' for k, v in correlations.items()])}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <div class="bg-white p-6 rounded-lg shadow-sm border border-gray-100 mb-8">
            <h2 class="text-xl font-bold text-gray-700 mb-4">Feature Distribution Statistics (Top 20)</h2>
            <div class="overflow-x-auto">
                <table class="min-w-full bg-white text-left text-sm">
                    <thead>
                        <tr class="bg-gray-100">
                            <th class="p-3">Feature</th>
                            <th class="p-3">Mean</th>
                            <th class="p-3">Std Dev</th>
                            <th class="p-3">Min</th>
                            <th class="p-3">Max</th>
                        </tr>
                    </thead>
                    <tbody>
                        {"".join([f'<tr class="border-b"><td class="p-3 font-mono font-semibold">{s["feature"]}</td><td class="p-3">{s["mean"]:.4f}</td><td class="p-3">{s["std"]:.4f}</td><td class="p-3">{s["min"]:.4f}</td><td class="p-3">{s["max"]:.4f}</td></tr>' for s in dist_stats])}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

    <script>
        const ctxTrain = document.getElementById('trainClassChart').getContext('2d');
        new Chart(ctxTrain, {{
            type: 'bar',
            data: {{
                labels: {json.dumps(list(train_classes.keys()))},
                datasets: [{{
                    label: 'Count',
                    data: {json.dumps(list(train_classes.values()))},
                    backgroundColor: '#4F46E5',
                    borderRadius: 4
                }}]
            }},
            options: {{
                responsive: true,
                maintainAspectRatio: false,
                scales: {{
                    y: {{ beginAtZero: true }}
                }}
            }}
        }});
    </script>
</body>
</html>
"""
        with open(filepath, "w") as f:
            f.write(html_content)
        logger.info(f"Dataset Quality Report generated successfully at {filepath}")
