class BacktestReport:
    @staticmethod
    def generate(stats, strategy_name, symbol, timeframe, period_start, period_end):
        report = []
        report.append("================================================")
        report.append("                BACKTEST REPORT                 ")
        report.append("================================================")
        report.append(f"Strategy:    {strategy_name}")
        report.append(f"Symbol:      {symbol}")
        report.append(f"Timeframe:   {timeframe}")
        report.append(f"Period:      {period_start} -> {period_end}")
        report.append("------------------------------------------------")
        report.append("Trades")
        report.append("------------------------------------------------")
        report.append(f"Total Trades:    {stats.get('total_trades', 0)}")
        report.append(f"Wins:            {stats.get('wins', 0)}")
        report.append(f"Losses:          {stats.get('losses', 0)}")
        report.append(f"BreakEven:       {stats.get('breakeven', 0)}")
        report.append(f"Win Rate:        {stats.get('win_rate', 0):.2f}%")
        report.append("------------------------------------------------")
        report.append("Performance")
        report.append("------------------------------------------------")
        report.append(f"Net Profit:      ${stats.get('net_profit', 0):.2f}")
        report.append(f"Profit Factor:   {stats.get('profit_factor', 0):.2f}")
        report.append(f"Expectancy:      ${stats.get('expectancy', 0):.2f}")
        report.append(f"Max Drawdown:    {stats.get('max_drawdown_pct', 0):.2f}%")
        report.append(f"Average R:       {stats.get('avg_r_multiple', 0):.2f}")
        report.append(f"Final Balance:   ${stats.get('final_balance', 0):.2f}")
        report.append("------------------------------------------------")
        report.append("Risk & Durations")
        report.append("------------------------------------------------")
        report.append(f"Avg Win:         ${stats.get('avg_win', 0):.2f}")
        report.append(f"Avg Loss:        ${stats.get('avg_loss', 0):.2f}")
        report.append(f"Cons. Wins:      {stats.get('max_cons_wins', 0)}")
        report.append(f"Cons. Losses:    {stats.get('max_cons_losses', 0)}")
        report.append(f"Avg Duration:    {stats.get('avg_duration_seconds', 0)/60:.1f} min")
        report.append("================================================")

        return "\n".join(report)
