import os
import csv
import logging
import threading
from typing import Dict, List, Any, Optional
import pandas as pd
from datetime import datetime
from Core.signal_candidate import SignalCandidate

logger = logging.getLogger("SignalRecorder")

class SignalRecorder:
    """
    Purpose:
        A thread-safe, production-grade logger and database recorder for every signal candidate
        generated by the trading strategies. It logs accepted, rejected, expired, or cancelled
        signals to support subsequent retraining of classifiers, level break probability models,
        trade quality models, and reinforcement learning agents.
    """
    def __init__(self, filepath: str = "Logs/signal_records.csv"):
        self.filepath = filepath
        self._lock = threading.Lock()

        # Ensure target directory exists
        os.makedirs(os.path.dirname(os.path.abspath(self.filepath)), exist_ok=True)

    def record_candidate(
        self,
        candidate: SignalCandidate,
        rejection_reason: str = "",
        outcome_metrics: Optional[Dict[str, Any]] = None
    ) -> None:
        """
        Record a signal candidate with its state snapshots and optional outcome metrics.
        Flattens nested dictionaries into columns.
        """
        outcome = outcome_metrics or {}

        flat_record = {
            "signal_id": candidate.signal_id,
            "strategy_name": candidate.strategy_name,
            "strategy_version": candidate.strategy_version,
            "symbol": candidate.symbol,
            "timeframe": candidate.timeframe,
            "timestamp": candidate.timestamp,
            "direction": candidate.direction,
            "signal_type": candidate.signal_type,
            "entry_price": candidate.entry_price,
            "stop_loss": candidate.stop_loss,
            "take_profit": candidate.take_profit,
            "risk_reward": candidate.risk_reward,
            "market_state": candidate.market_state,
            "trend": candidate.trend,
            "signal_quality": candidate.signal_quality,
            "confidence": candidate.confidence,
            "risk_multiplier": candidate.risk_multiplier,
            "reasoning": candidate.reasoning,
            "priority": candidate.priority,
            "status": candidate.status,
            "rejection_reason": rejection_reason or outcome.get("rejection_reason", ""),

            # Outcome metrics (if trade was executed and eventually closed)
            "outcome": outcome.get("outcome", "PENDING"), # WIN, LOSS, BREAKEVEN, REJECTED, etc.
            "mfe": outcome.get("mfe", 0.0),               # Maximum Favorable Excursion
            "mae": outcome.get("mae", 0.0),               # Maximum Adverse Excursion
            "r_multiple": outcome.get("r_multiple", 0.0), # Realized R-multiple
            "time_in_trade_sec": outcome.get("time_in_trade_sec", 0.0),
            "exit_reason": outcome.get("exit_reason", ""),
            "exit_price": outcome.get("exit_price", 0.0),

            # Reserved future label columns
            "label_market_state_retrain": outcome.get("label_market_state_retrain", ""),
            "label_level_break_retrain": outcome.get("label_level_break_retrain", ""),
            "label_trade_quality_retrain": outcome.get("label_trade_quality_retrain", ""),
        }

        # Flatten Snapshots (Prefixing to prevent key collision)
        for k, v in candidate.strong_candle_info.items():
            if isinstance(v, dict):
                for sub_k, sub_v in v.items():
                    flat_record[f"strong_candle_{sub_k}"] = sub_v
            else:
                flat_record[f"strong_candle_{k}"] = v

        for k, v in candidate.refusal_info.items():
            if isinstance(v, dict):
                for sub_k, sub_v in v.items():
                    flat_record[f"refusal_{sub_k}"] = sub_v
            else:
                flat_record[f"refusal_{k}"] = v

        for k, v in candidate.market_structure_snapshot.items():
            flat_record[f"structure_{k}"] = v

        for k, v in candidate.supply_demand_snapshot.items():
            flat_record[f"zone_{k}"] = v

        for k, v in candidate.ml_predictions.items():
            flat_record[f"ml_{k}"] = v

        with self._lock:
            try:
                file_exists = os.path.exists(self.filepath) and os.path.getsize(self.filepath) > 0

                # We will read existing keys if file exists to keep header aligned
                fieldnames = list(flat_record.keys())

                if file_exists:
                    try:
                        # Inspect columns to keep consistent schema
                        df_temp = pd.read_csv(self.filepath, nrows=1)
                        existing_cols = df_temp.columns.tolist()
                        # Ensure any new column gets filled, and preserve existing file header
                        for col in existing_cols:
                            if col not in flat_record:
                                flat_record[col] = ""
                        # Re-order flat_record keys to match existing file order
                        aligned_record = {}
                        for col in existing_cols:
                            aligned_record[col] = flat_record[col]
                        # append any new columns
                        for col in flat_record:
                            if col not in existing_cols:
                                aligned_record[col] = flat_record[col]
                        flat_record = aligned_record
                        fieldnames = list(flat_record.keys())
                    except Exception:
                        pass

                # Write / Append to CSV safely
                with open(self.filepath, "a", newline="", encoding="utf-8") as csvfile:
                    writer = csv.DictWriter(csvfile, fieldnames=fieldnames, extrasaction="ignore")
                    if not file_exists:
                        writer.writeheader()
                    writer.writerow(flat_record)

                logger.debug(f"Recorded signal candidate {candidate.signal_id} to {self.filepath}")
            except Exception as e:
                logger.error(f"Failed to record signal candidate: {e}", exc_info=True)

    def update_signal_outcome(self, signal_id: int, outcome_metrics: Dict[str, Any]) -> bool:
        """
        Updates an existing recorded signal outcome using its signal_id.
        This closes the loop on executed signals by writing outcomes (MFE, MAE, realized R multiple).
        """
        with self._lock:
            if not os.path.exists(self.filepath) or os.path.getsize(self.filepath) == 0:
                logger.warning(f"Cannot update outcome: Recorder file {self.filepath} does not exist or is empty.")
                return False

            try:
                df = pd.read_csv(self.filepath)
                mask = df["signal_id"] == signal_id
                if not mask.any():
                    logger.warning(f"Signal ID {signal_id} not found in {self.filepath}.")
                    return False

                # Update columns
                for col, val in outcome_metrics.items():
                    if col not in df.columns:
                        df[col] = None # add column if missing
                    df.loc[mask, col] = val

                df.to_csv(self.filepath, index=False)
                logger.info(f"Successfully updated outcome for signal ID {signal_id}")
                return True
            except Exception as e:
                logger.error(f"Error updating signal outcome {signal_id}: {e}", exc_info=True)
                return False
